services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
  notification:
    environment:
      EmailSettings__GmailAddress: dare02dance@gmail.com
      EmailSettings__AppPassword: hjmfztozvfuizajx
      RabbitMq__Host: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__VirtualHost: /
      RabbitMq__QueueName: notifications
    secrets:
      - rabbitmq_username
      - rabbitmq_password
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    secrets:
      - rabbitmq_username
      - rabbitmq_password
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_username
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_password
    secrets:
      rabbitmq_username:
       file: ./secrets/rabbitmq_username.txt
      rabbitmq_password:
       file: ./secrets/rabbitmq_password.txt