services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
  notification:
    environment:
      EmailSettings__GmailAddress: dare02dance@gmail.com
      EmailSettings__AppPassword: zglaezxshwqdftkl