<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Persistence\Migrations\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
      <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
      <PackageReference Include="MediatR" Version="14.2.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
      <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.11" />
      <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.0" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DareToDance.Domain\DareToDance.Domain.csproj" />
    </ItemGroup>

</Project>
