syntax = "proto3";

option csharp_namespace = "DareToDance.Notifications.Grpc";

package notification;

service NotificationService {
  rpc SendNotification (SendNotificationRequest) returns (SendNotificationResponse);
}

message SendNotificationRequest {
  string recipient = 1;               
  Channel channel = 2;
  string template = 3;                
  map<string, string> variables = 4;  
}

message SendNotificationResponse {
  bool accepted = 1;
  string tracking_id = 2;             
}

enum Channel {
  EMAIL = 0;
  SMS = 1;
  PUSH = 2;
}
