@host=http://localhost:5015
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJEYXJlVG9EYW5jZSIsImlzcyI6IkRhcmVUb0RhbmNlIiwiZXhwIjoxNzgzNzE5NDU5LCJpYXQiOjE3ODM3MTU4NTksIm5iZiI6MTc4MzcxNTg1OSwic3ViIjoiODg0NDFhMTItOWNlOS00OWZjLTk5Y2YtNDIyNjczOWU2OWU4IiwiZW1haWwiOiJuaWtvbGFAYW5kcmljLmNvbSIsImdpdmVuX25hbWUiOiJOaWtvbGEiLCJmYW1pbHlfbmFtZSI6IkFuZHJpYyIsImp0aSI6Ijc3Zjk5ZWI1LTFlNTYtNDU2NS05MGZhLTBkNjMwMmY1YWQxMyJ9.f-RkxUsWCyLx9FvPGjK5AV9fhbEDKzogGjEa8Tr77_Q


GET {{host}}/users/me
Authorization: Bearer {{token}}
